### ISSUE TITLE
Timeouts on long tests

### ISSUE THREAD

**Issue by Uko** [hpi-swa/smalltalkCI#154]
Travis times out if there is no output for 10 minutes.

And naturally tests do not generate any output, so if they are running more than 10 min, the build is aborted. There is a documentation about this on https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

I think that it's a nice feature to abort builds, but maybe we can add some config that will allow to run the command prepended with `travis_wait` and a specified amount of time

**Comment by dalehenrich** [comment]
in builderCI I added a forked process that dumped a line to stdout every couple of minutes and that trick could be used here ...

**Comment by fniephaus** [comment]
I know about the limitation and I think 10 minutes is a good timeout value. builderCI periodically printed something to stdout and smalltalkCI now prints the Transcript directly to stdout. That's how we made sure that the build process does not hit the limit.
I'd say it's a little weird that a test runs longer than 10 minutes without printing anything, but that's not a reason for not supporting it.
Since this is a Travis limitation, I'd say we could get away with changing the timeout with an environment variable. I'd also prefer to use Travis' `travis_wait` as mentioned by @Uko. BTW [it works very similar](https://github.com/travis-ci/travis-build/blob/fadf22afd9a385449aeb22d2544642b089593b81/lib/travis/build/templates/header.sh#L112-L149) to the builderCI approach.
The change should be fairly simple and I'm happy to take care of it...

**Comment by Uko** [comment]
I know that it's weird that there are such tests. But I'm working on the critiques for Pharo, and now I've added a set of test which run all rules on all the possible candidates (methods, classes, packages, etc) and check if there are no exceptions. This takes time :)

**Comment by fniephaus** [comment]
Benchmarks could also run multiple minutes if you need performance tests for your project...
But don't forget that Travis builds don't run forever 😉

**Comment by fniephaus** [comment]
Shall we call the env var `$SMALLTALK_CI_WAIT_TIME` or `$SMALLTALK_CI_TIMEOUT`?
