### ISSUE TITLE
Loading code with gitfiletree or similar

### ISSUE THREAD

**Issue by Uko** [hpi-swa/smalltalkCI#196]
Hi, in case a project uses mata-data-less format, the versions loaded into the image have a very limited representation (in terms of author name, version name, commit message, etc…). And if publish your project from Travis it is not nice. Do you think that it may be possible to load the code by cloning the git repo (I think travis is doing this by default) and loading the code with gitfiletree?

(I know there can be some issues, but theoretically baseline should be enough to know what to load)

**Comment by fniephaus** [comment]
Hi @Uko, I don't have any experience with metadata-less FileTree yet. smalltalkCI loads the project through a Metacello baseline/configuration. I thought that in Pharo, Metacello will load a baseline the right way already. But how would you load your baseline the way you want it?

**Comment by dalehenrich** [comment]
@uko are you referring to the fact that gitfiletree fabricates a version history for each package? 

Personally I find the gitfiletree approach a little disturbing, because even though version numbers are fabricated they are based upon the number of commits in the history and I get confused when looking at history for different branches since the same numbers do not represent the same commit ... 

I've felt that the "right answer" is to break from the Monticello way for metadataless packages ... package history is useful, but the author and "package version" should be just eliminated from the package name in the image ... 

I understand that gitfiletree needed to "wear sheeps clothing" tofit and I applaud the work that @ThierryGoubier did to popularize git with pharo, but I think moving forward the right model is to simplify the package name and provide commit history that does not mask the git information ... this kind of history should be provided at the method and class level as well ...

**Comment by dalehenrich** [comment]
@uko, I think that you are referring to the fact that Pharo FileTree dose not (or did not at the time) support metadataless loading ... @ThierryGoubier had only added that feature to gitfiletree and did not support it for FileTree ... perhaps that has changed by now ... I added metadataless support for GemStone FileTree and @krono added metadeataless support for Squeak ...

**Comment by peteruhnak** [comment]
Just as a note, most of my projects are metadata-ess gitfiletree and I didn't have any problem yet, so I am not sure what problem @Uko is running into (I also publish the built images and had no problem there either).

**Comment by peteruhnak** [comment]
@Uko maybe better way forward would be to load the project with iceberg instead of gitfiletree... it has the same underlying metadata-less filetree, but iceberg would be more practical to handle versions in-image

**Comment by dalehenrich** [comment]
At the moment I don't think iceberg is in the standard pharo release and smalltalkCI tries to keep the number of external dependencies to a minimum, so that it can be used to test things like iceberg itself ...

When iceberg becomes the default package loader for Pharo (via Metacello), then it will be used, but there are a number of moving parts here ... 

The absolute simplest solution is to add metadataless support to filetree for Pharo ... but this is something that needs to be done by Pharo (and included in the base image) and used by smalltalkCI...

**Comment by fniephaus** [comment]
Is there an ETA for Iceberg shipping with Pharo? It's currently only supported in Pharo-6 and doesn't look to be backward-compatible (please correct me if I'm wrong).
As soon as Iceberg ships with a Pharo release, we can implement a corresponding load spec for smalltalkCI.
On the other hand, it feels like all approaches are based on metadata-less FileTree/Metacello which might be the better level of abstraction.

**Comment by peteruhnak** [comment]
Iceberg is planned to be integrated early Pharo 7 (so couple weeks I guess). But this whole feature is more of a cosmetic change (unless @Uko was experiencing some breaking problems, which he didn't describe) - so maybe not having it for older Pharo version's wouldn't be a problem.

**Comment by fniephaus** [comment]
I think this can be closed now that Pharo has proper support for Git. Please reopen if you think something in smalltalkCI still needs to be changed.
