### ISSUE TITLE
Add support for `./pharo Pharo.image config ...`?

### ISSUE THREAD

**Issue by fniephaus** [hpi-swa/smalltalkCI#21]
@peteruhnak mentioned in #20 that Pharo users often use the same script (see below) for their [Jenkins CI builds](https://ci.inria.fr/pharo-contribution/).

I believe it'd make sense to add support for the following:
```bash
./pharo $JOB_NAME.image config $REPO ConfigurationOfSton --install=$VERSION
```

Any objections/suggestions?

For the record, here's the full script again:
```bash
# jenkins puts all the params after a / in the job name as well :(
export JOB_NAME=`dirname $JOB_NAME`

wget --quiet -O - get.pharo.org/$PHARO+$VM | bash

./pharo Pharo.image save $JOB_NAME --delete-old
./pharo $JOB_NAME.image --version > version.txt

REPO=http://smalltalkhub.com/mc/HardCodedRepository/$JOB_NAME/main
./pharo $JOB_NAME.image config $REPO ConfigurationOfSton --install=$VERSION
./pharo $JOB_NAME.image test --junit-xml-output "$JOB_NAME.*"

zip -r $JOB_NAME.zip $JOB_NAME.image $JOB_NAME.changes

# clean up the workspace to not occupy too much stale space on the slaves
rm -rf *.image *.changes
```

**Comment by peteruhnak** [comment]
I should've explained the script.

The line `./pharo $JOB_NAME.image config $REPO ConfigurationOfSton --install=$VERSION` 

Loads the project itself (the name of the project is hardcoded here), however the line doesn't make much sense for us, no? Since we are working with baselines and git(hub) and not smalltalkhub/configurationof.

-----Original Message-----

**Comment by peteruhnak** [comment]
I should've explained the script.

The line `./pharo $JOB_NAME.image config $REPO ConfigurationOfSton --install=$VERSION` 

Loads the project itself (the name of the project is hardcoded here), however the line doesn't make much sense for us, no? Since we are working with baselines and git(hub) and not smalltalkhub/configurationof.

**Comment by fniephaus** [comment]
Can't `$REPO` be a local path and then it's possible to load a project via its configuration?
And a configuration can be exported just like a baseline, right?
Or am I missing something here?
I thought if Pharo users are mostly using configurations, why not adding support for it here?

**Comment by fniephaus** [comment]
Instead of using `./pharo Pharo.image config ...`, I have decided to use [this](https://github.com/hpi-swa/smalltalkCI/blob/6828ef8df6e2419682052282f753639a87c5d7ab/pharo/run.sh#L200-L210) for now.
