### ISSUE TITLE
Is there a way to not get 8 emails for each build that uses appveyor?

### ISSUE THREAD

**Issue by dalehenrich** [hpi-swa/smalltalkCI#222]
One email would be okay ... but 8 emails per build is a bit excessive ... I don't get any emails from travis and I'm not sure why appveyor has to send so much spam?

**Comment by dalehenrich** [comment]
Oh wait I get an email when a build fails and an email when the state changes ... which is nice ... I don't need to know about a 0.00000001% change in test coverage:)

**Comment by fniephaus** [comment]
I think you are talking about the [Coveralls comments](https://github.com/hpi-swa/smalltalkCI/pull/221#issuecomment-256150002). I'll turn them off, because they are really annoying. Turns out they don't manage to recognize that build jobs belong to the same build, so for each build their bot comments on a PR.

**Comment by fniephaus** [comment]
I've turned it off.
