### ISSUE TITLE
Code Coverage counts subclassResponsibility methods

### ISSUE THREAD

**Issue by gcotelli** [hpi-swa/smalltalkCI#260]
When using the code coverage support the methods implemented as subclassResponsibility ends up being reporter as not covered. 

When running the coverage report using the Test Runner in the image are correctly reported, but using the coveralls integration not. I don't known if this is an error in SmalltalkCI or just in the way coveralls make the calculation.

**Comment by fniephaus** [comment]
Hi @gcotelli,
What Smalltalk dialect are you using? Do you have a link to a project with this issue?
As far as I know, a method needs to be actually executed in order to be marked as covered. Therefore, it should also be marked as uncovered in the Test Runner, except if you have tested for `subclassResponsibility`.

**Comment by gcotelli** [comment]
Hi @fniephaus . I'm using Pharo 6. Take a look at this pull request: https://github.com/ba-st/Pharo-Kernel/pull/1 .
It's reported as 98.675% of coverage, but the only method shown without coverage is a subclassResponsibility one and the Pharo Test Runner reports that the coverage is complete. 

IMHO it is correct to no consider the methods implemented as subclassResponsibility as not covered, because the intention is that they are not executed.

**Comment by fniephaus** [comment]
Can you check what happens if you change `#categories` to `#packages` in [your `.smalltalk.ston`](https://github.com/ba-st/Pharo-Kernel/blob/ebc5c962fd048f3ae52e0c653bef5d14eae35bfd/.smalltalk.ston#L12)?
This should cause smalltalkCI to use `TestRunner>>addMethodsUnderTestIn:to:excludeClassesNotUnderTestFrom:` and maybe that filters out your subclassResponsibility method.
However, I wonder, shouldn't you mark `AssertionFailurePolicy` as abstract (as in overriding `AssertionFailurePolicy class>>isAbstract`)?

**Comment by gcotelli** [comment]
I've changed the .smalltalk.ston as suggested and it works ok this way.

**Comment by fniephaus** [comment]
That's great. The test coverage test is based on packages in the image, smalltalkCI does support categories and single classes, but as you saw, the behavior is a little bit different.
I see if I can improve the docs to make this more clear.
