### ISSUE TITLE
Ensure coveralls_data.json is a valid JSON file

### ISSUE THREAD

**Issue by JurajKubelka** [hpi-swa/smalltalkCI#270]
I have the following issue executing the coverage:

```
STONReaderError: At character 341: Cannot read coveralls_data.json.
[ :error | 
error
	messageText: 'Cannot read ' , self class coverallsDataFilename , '.'.
error signal ] in SCIPharoCodeCoverage>>readCoverallsData in Block: [ :error | ...
...
FileReference(AbstractFileReference)>>readStreamDo:
[ ^ reference readStreamDo: [ :stream | STON fromStream: stream ] ] in SCIPharoCodeCoverage>>readCoverallsData in Block: [ ^ reference readStreamDo: [ :stream | STON fromS...etc...
BlockClosure>>on:do:
SCIPharoCodeCoverage>>readCoverallsData
```
[stack.txt](https://github.com/hpi-swa/smalltalkCI/files/925733/stack.txt)

See the log on [Travis](https://travis-ci.org/JurajKubelka/DiscordSt/jobs/221963324#L401). It worked a [two commits before](https://travis-ci.org/JurajKubelka/DiscordSt/jobs/221959139#L470). But technically there are no changes between those two commits (the one was reverted).

How can I debug it? It does not work the same way locally `smalltalkCI.sh --headful` despite the fact that I execute it in `headful` mode and I rewrite `isCoverageTestingEnabled` to `true`. It is skipped anyway in `run:spec:in:`, writing message _"Coveralls data is not available. Skipping coverage testing..."_

**Comment by fniephaus** [comment]
Hi @JurajKubelka,
This indeed is currently quite hard to debug. Coverage results are send to coveralls from within the image, but coveralls needs more information about the current git commit. That's why smalltalkCI currently creates a file with this info and then the coverage runner adds the coverage results and uploads everything.
To answer your question: if you want to debug this locally, you currently need to add a `coveralls_data.json` [which has to look like this](https://github.com/hpi-swa/smalltalkCI/blob/e1204ea7c6256ef01109f78a285566aa90ddaf7e/helpers.sh#L272-L294) to the directory of your build. Probably best you prepare the file first, run smalltalkCI in debug mode, so that you can copy the file into the build directory and then press proceed in the debugger. Don't forget that you also need to manually save and close the image after the load phase.
Hope this helps and let me know if you need more help.

BTW: I also found your bug while writing this: the generated [`coveralls_data.json`](https://github.com/hpi-swa/smalltalkCI/blob/e1204ea7c6256ef01109f78a285566aa90ddaf7e/helpers.sh#L272-L294) does not contain escaped quotes. And since your commit contains quotes, the JSON file is invalid. I'm renaming the issue and leave it open until there is a fix...

**Comment by JurajKubelka** [comment]
Hi @fniephaus, 

thank you for the explanation! I understand that it will work with the next commit without quotes.

I have the impression that the solution is to change [helpers.sh#L257](https://github.com/hpi-swa/smalltalkCI/blob/e1204ea7c6256ef01109f78a285566aa90ddaf7e/helpers.sh#L257) as the following: 

```
  output=$(git --no-pager log -1 --pretty=format:"${format_value}" | sed -e 's/"/\\"/g')
```

**Comment by fniephaus** [comment]
Thank for the suggestion, but actually I was thinking about a different solution: smalltalkCI has support for environment variables for some time now, so instead of creating a file, it might as well just use environment variables, which might be better in this case...

**Comment by JurajKubelka** [comment]
For the documentation purpose: 

Apparently it is not just about double quotes, I have accidentally written a "strange" character to the commit message. See https://travis-ci.org/JurajKubelka/PharoSprint/jobs/244586908#L662

The strange character is visible here: https://github.com/JurajKubelka/PharoSprint/commit/8d4578127b506f05b3555db39215fc152c8e2a13 right between "ges;�user can"

**Comment by fniephaus** [comment]
Thanks, I'll have a look into this soon!
