### ISSUE TITLE
Dependency Caching for GemStone

### ISSUE THREAD

**Issue by dalehenrich** [hpi-swa/smalltalkCI#31]
Submitting as a separate issue from https://github.com/hpi-swa/smalltalkCI/issues/28, since using [dependency caching](https://docs.travis-ci.com/user/migrating-from-legacy/#How-Do-I-Cache-Dependencies-and-Directories%3F) is an optimization to be applied after https://github.com/hpi-swa/smalltalkCI/issues/28 is finished

**Comment by fniephaus** [comment]
Just to make sure: your idea is to cache the GemStone vm after it has been set up, right?

**Comment by dalehenrich** [comment]
I was thinking along the lines of caching the GemStone and Pharo client 
downloads as they are not likely to be changed during abuild ... If it's 
feasible to cache more then that would be even better ...

**Comment by fniephaus** [comment]
I don't think the build wouldn't benefit much if you only cache the download files. The caching basically uploads a zip file to S3 and downloads and unpacks it again during the next build.
You might want to read this if you haven't already:
https://docs.travis-ci.com/user/caching/#Things-not-to-cache

However, it might still make sense to cache the images if it's possible and faster to update them.

**Comment by dalehenrich** [comment]
Good information ... thanks!

**Comment by fniephaus** [comment]
It doesn't seem to make sense to cache images or vms, because you want a fresh image per build and a vm is just a zip download. So uploading this stuff to S3 via Travis is not going to speed anything up, it's only more expensive for Travis.
However, caching the `github-cache` folder does make sense in order to avoid hitting GitHub's API limit.
I have opened #36 for that.
