### ISSUE TITLE
Allow explicit usage of smalltalkCI

### ISSUE THREAD

**Issue by guillep** [hpi-swa/smalltalkCI#327]
Hi, I want to instrument the travis script run by smalltalk CI to use a travis_wait. But I cannot do that because the `.travis.yml` does not explicitly call the test script.

This is of course related because it looks like something carved in the following design decision: when we use smalltalkCi, we should touch the `.travis.yml` file as less as possible, and put most of the things we have in the `.ston` file. This happens for example also in issue #259.

Why don't you want to add entries in the .travis.yml file? Sometimes I need to install and configure other dependencies (such as databases) (i.e., issue #190). Sometimes I need to access the produced output (i.e., issue #148).

Now, I like that smalltalk ci manages in a **polymorphic** way how the different dialects/environments are installed, and how tests are run. However, I think giving some more control to the user could be nice, and simplify some things.

For example, I imagine smalltalk ci could, instead of running my tests implicitly, just export a 
`smalltalkCi` script (such as `pytest` for python for example). Then users could write the script in their yaml file as they want:

```yaml
script:
    smalltalkCi #Runs by default the main .smalltalk.ston file
    smalltalkCi .mysmalltalk.ston #Runs the one we said
    travis_wait smalltalkCi
```

This would come along with:
- the ability to install and configure non-smalltalk resources as normal parts of the travis `before_script:`, `before_install:`, and so on...
- the ability to choose if two `.smalltalk.ston` files should run in the same or different builds
- simplify the usage and management of matrixes

I was checking 

https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/script/smalltalk.rb

and I imagine the part where the `run.sh` is the

```ruby
        def script
          super

          sh.cmd "$SMALLTALK_CI_HOME/run.sh"
        end
```

I wouldn't know however how to manage backwards compatibility. (Can we ask travis if script is defined?)

**Comment by fniephaus** [comment]
Hi @guillep,
I must admit that I didn't quite understand your concern/suggestion, but let me try to comment anyway.

First of all, there is [an option](https://github.com/hpi-swa/smalltalkCI#travis-specific-options) to increase the TravisCI timeout which actually uses `travis_wait`.

Moreover, the `.travis.yml` template in smalltalkCI's readme does not contain a `script` override, because the default is already provided in the [`smalltalk.rb`](https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/script/smalltalk.rb#L72) as you already mentioned. However, it is of course possible to override that default, e.g. with:
```yml
...
script:
  - "$SMALLTALK_CI_HOME/run.sh"
  - "$SMALLTALK_CI_HOME/run.sh" .mysmalltalk.ston
  - travis_wait "$SMALLTALK_CI_HOME/run.sh"
...
```
I might have a look at how we can provide a `smalltalkCI` shortcut on Travis, so you can just use `smalltalkCI` instead of `$SMALLTALK_CI_HOME/run.sh`.
Anyway, it is already possible to use `before_script`, etc. as usual and to run more than one config in the same build. The reason why things are designed in the way they are is that we want to keep the common use cases brief and simple while also allowing more advanced use cases for power users.

I hope this makes sense. Let me know if you have any questions.

Fabio

**Comment by guillep** [comment]
Ah! Actually I got mislead by the documentation and existing issues!

Because of the fact that `script` was magically "inferred" it was not clear enough to me that you could override it.

I think we can close this issue, I'll make a PR to enhance the documentation with your comment.

Thanks!

**Comment by fniephaus** [comment]
Ha, no worries. Thanks! :)
