### ISSUE TITLE
Pharo-alpha failures ... expected?

### ISSUE THREAD

**Issue by dalehenrich** [hpi-swa/smalltalkCI#339]
[recent builds for Pharo-Alpha are failing](https://travis-ci.org/dalehenrich/smalltalkCI/jobs/303302152):

 ![image](https://user-images.githubusercontent.com/623951/32963144-de9d1be4-cb83-11e7-9a58-3df097cbf7c5.png)

**Comment by dalehenrich** [comment]
Apparently the `Pharo-Alpha` build is an expected failure, but you have to read the *fine print* to tell ... apparently expected failures aren't put into an obvious category with this new build format you are using for SmalltalkCI ... and of course my build **actually** failed because of failure further down the list --- that I didn't see either ...

**Comment by fniephaus** [comment]
Pharo-alpha currently fails due to an `unknown option: --nodisplay` error. Apparently, the VM's cli has changed. Could someone from the Pharo community (maybe @jecisc again 😅) please have a look at this? [Here's an example build failure.](https://travis-ci.org/hpi-swa/smalltalkCI/jobs/567793220#L677)

**Comment by fniephaus** [comment]
I think the `--nodisplay` issue has been fixed by the Pharo team by now.
