### ISSUE TITLE
Cache github-package folder

### ISSUE THREAD

**Issue by fniephaus** [hpi-swa/smalltalkCI#36]
Sometimes builds can hit a GitHub API limit ([example](https://github.com/hpi-swa/smalltalkCI/issues/28#issuecomment-169502593)), because Metacello uses the API for project loading purposes.

Caching the `github-package` folder may resolve that problem (as [suggested](https://github.com/hpi-swa/smalltalkCI/issues/28#issuecomment-169794903) by @dalehenrich).

smalltalkCI already has a build folder structure, but for Travis it could always use the same build folder which then can be [cached by Travis](https://docs.travis-ci.com/user/caching/).

**Comment by dalehenrich** [comment]
The apil rate limit problem was actually addressed by dalehenrich/metacello-work#385, so this bug is fixed without needing to cache the github-cache and can be closed

I do think that I can speed up builds by caching a intermediate/bootstrapped version of the stone  ... so I think I will open a new issue (Issue #31 would be appropriate, but it's been closed) ... for that work

**Comment by fniephaus** [comment]
Obsolete, see https://github.com/hpi-swa/smalltalkCI/issues/36#issuecomment-197618614.
