### ISSUE TITLE
Do not load STON dependency in Pharo 6.0 and later

### ISSUE THREAD

**Issue by fortizpenaloza** [hpi-swa/smalltalkCI#418]
Hi, my build is failing due to a timeout while trying to load SmalltalkCI's dependency on STON

```
Project: Ston stable [0.27]
...RETRY->STON-Core-SvenVanCaekenberghe.90
...RETRY->STON-Core-SvenVanCaekenberghe.90ConnectionTimedOut: Cannot connect to 204.246.122.142:80
```

See https://travis-ci.com/ba-st/Superluminal/jobs/192275250

**Comment by fortizpenaloza** [comment]
I will be happy to collaborate via a PR but I've a few questions. 

- Do the `BaselineOf` needs to declare a dependency on STON for #pharo? Can I define that dependency just for older pharo versions?
- Should I use `master` of https://github.com/svenvc/ston?

**Comment by fniephaus** [comment]
I hope this was just a temporary problem. SmalltalkHub seem to be up and running again.

RE your questions:
Yes, I think it should be possible to depend on external STON only in older Pharo images. For that, we probably need to adjust [BaselineOfSmalltalkCI](https://github.com/hpi-swa/smalltalkCI/blob/ab4ff34b34bf91e7f73c876ab8b616c7030c5f3b/repository/BaselineOfSmalltalkCI.package/BaselineOfSmalltalkCI.class/instance/baseline..st#L45). Since when does Pharo come with STON pre-installed?

**Comment by fortizpenaloza** [comment]
Hi @fniephaus ,

It was a temporary problem, thanks!

STON-Core and STON-Tests are part of the image since Pharo 6.0 (#60508). This version is the older available from get.pharo.org so I can provide information for older versions.

**Comment by fniephaus** [comment]
Good to know, let's keep this open as a reminder to not load STON in Pharo 6.0 and later.

**Comment by jecisc** [comment]
IIRC STON was introduced in Pharo 5 and not 6 ;)

**Comment by jecisc** [comment]
I just checked and I confirm.
