### ISSUE TITLE
Travis job for GemStone64-3.5.0 on Linux fails

### ISSUE THREAD

**Issue by Rinzwind** [hpi-swa/smalltalkCI#445]
The Travis job for GemStone64-3.5.0 on Linux fails, see: https://travis-ci.org/Rinzwind/smalltalkCI/jobs/619559381#L525-L532.

The error is:

```
The 32-bit libraries required by Pharo have not been installed on this system. :: downloadSmalltalkClient -v Pharo3.0 -d /home/travis/build/Rinzwind/smalltalkCI/_builds/GsDevKit_home/shared/pharo
Error on or near line 76 :: create_gs_server_image -d /home/travis/build/Rinzwind/smalltalkCI/_builds/GsDevKit_home/shared/pharo gsDevKitCommandLine :: create_gs_server_image -d /home/travis/build/Rinzwind/smalltalkCI/_builds/GsDevKit_home/shared/pharo gsDevKitCommandLine
Error on or near line 74 :: devKitCommandLine createSmalltalkCIStoneNew travis 3.5.0 DataCurator swordfish  :: devKitCommandLine createSmalltalkCIStoneNew travis 3.5.0 DataCurator swordfish 
Error on or near line 203 :: createStone travis 3.5.0 :: createStone travis 3.5.0

Error with status code 1:
125 gemstone::prepare_stone /home/travis/build/Rinzwind/smalltalkCI/gemstone/run.sh
The command "bin/smalltalkci --self-test" exited with 1.
```

**Comment by fniephaus** [comment]
Interesting, I think it's because you try to use a 64bit GemStone with 32bit Pharo clients. This could be supported, but isn't at the moment I think. What do you think, @dalehenrich?

**Comment by Rinzwind** [comment]
I'm not sure if it was clear that this is a build of the smalltalkCI project itself (using a fork that just mirrors the main repository). The tested commit is 4b2483d, the same one as in https://travis-ci.org/hpi-swa/smalltalkCI/builds/594603060.

It seems a different version of Ubuntu was used in the build for my fork though: Ubuntu 14.04.5 LTS (https://travis-ci.org/hpi-swa/smalltalkCI/jobs/594603063#L19) versus Ubuntu 16.04.6 LTS (https://travis-ci.org/Rinzwind/smalltalkCI/jobs/619559381#L19).

**Comment by fniephaus** [comment]
Oh right, I missed that for some reason. What happens if you force Ubuntu 14 with `dist: trusty` in the `.travis.yml`?

**Comment by dalehenrich** [comment]
Sorry for coming in late to the party ... this particular error occurs when `pharo -h` fails to respond with a 0 exit code ... it **could** be caused by missing 32 bit libraries required by pharo or it could be caused by a change in the behavior of the vm ... I have seen cases where the pharo vm exits with a non-zero exit code when help is requested ... I've seen a flurry of travis failures for CRON jobs in the last week (haven't had time to check them all out), but the [one that I looked at failed and had been prviously passing until a run last week](https://travis-ci.org/GsDevKit/ston/jobs/618008760?utm_medium=notification&utm_source=github_status) ... has something changed recently with support for 32 bit libraries?

**Comment by dalehenrich** [comment]
A number of the GemStone projects are still dependent upon 32 bit Pharo libraries being present and an even greater number run tests against 32 bit pharo, so if 32 bit Pharo library support could be enabled (again?) that would be useful ...

**Comment by fniephaus** [comment]
With regard to the dependencies, would it be sufficient to install Pharo's 32bit dependencies when running on GemStone (see [here](https://github.com/travis-ci/travis-build/blob/8cbe6ab2593f5ec3099c03009c125a654763804e/lib/travis/build/script/smalltalk.rb#L24-L39)). I still don't understand why this used to work. I'm guessing it's because of Ubuntu 16.04?

**Comment by dalehenrich** [comment]
I'm not quite sure you what you are asking?  For GsDevKit_home, [GsDevKit_home has done this](https://github.com/GsDevKit/GsDevKit_home/blob/master/bin/utils/installOsPrereqs#L39-L77) for years now and it was done for 14.04 through 18.04 so what was done for 14.04 was also needed for 16.04 ... so AFAIK, the os requirements haven't changed for 14.04, 16.04 or 18.04 ... of course, it is possible that pharo is downloading a new vm for the older versions of Pharo and perhaps the prerequisites for the new vm have changed? I am not in the habit of downloading new vms every week in my daily work, so I wouldn't know about prereq changes ... if that is indeed the case ... Are there travis ci jobs for Pharo3.0 other than the ones for GemStone?

**Comment by dalehenrich** [comment]
... pretty much all of the [GemStone travis jobs are now failing](https://travis-ci.org/dalehenrich/Seaside) .... I don't have the cycles right now to track this down as I hve bigger fish to fry at the moment ... but as I soon as I take care of this "big fish" i will have time to look at this, but at the moment I don't think it could be related to a change in the os ... 

GsDevKit_home will install pharo prereqs as part of it's install process, but it is [being skipped](https://travis-ci.org/dalehenrich/Seaside/jobs/620204955#L266) --- I checked that [this step was also skipped a year ago in a successful build](https://travis-ci.org/dalehenrich/Seaside/jobs/477594440#L982) ... which implies that GemStone has been relying on SmalltalkCI to properly install the Pharo 32 bit prereqs and I don't know know where to look to make sure that the prereqs are being installed correctly ... did anything change in smalltalkCI or Travis CI in the last week?

**Comment by fniephaus** [comment]
No, nothing has changed recently...but that also means smalltalkCI's tests haven't run in a while. I've triggered a build manually: https://travis-ci.org/hpi-swa/smalltalkCI/builds/620321459

**Comment by fniephaus** [comment]
Looks like the Gemstone build is failing: https://travis-ci.org/hpi-swa/smalltalkCI/jobs/620321462#L4

Has something changed in GsDevKit_Home recently?

**Comment by dalehenrich** [comment]
[7 days ago, GsDevKit_home master passed the majority of tests ... they nearly all use the 32 pharo vm}(https://travis-ci.org/GsDevKit/GsDevKit_home)

**Comment by dalehenrich** [comment]
In the one failing pharo 3.0 test, [the pharo download succeeded - the step that is consistently failing now](https://travis-ci.org/GsDevKit/GsDevKit_home/jobs/617471568#L1357-L1373) ...
This test was run against the last merge to master made in GsDevKit_home ... so what ever went wrong ...

[6 days ago, the pharo 32 bit vm started failing](https://travis-ci.org/GsDevKit/gsApplicationTools) ... so it isn't GsDevKit_home ...

**Comment by fniephaus** [comment]
I might have a look at this tomorrow...looks like we should double check if the Pharo files have changed

**Comment by dalehenrich** [comment]
... it's starting to look that way ...

[7 days ago, in the successful GsDevKit_home test with 32 bit clients 16.04 was being used](https://travis-ci.org/GsDevKit/GsDevKit_home/jobs/617471565)

I'm going to have to bet  on a 32 bit pharo vm change:)

**Comment by dalehenrich** [comment]
I'm still curious about how the 32 bit library prereqs have been met in the past ... GsDevKit_home has been skipping the prereq installation step forever ... and then 6 days ago the 32 bit support libraries are not there?

**Comment by dalehenrich** [comment]
[I've triggered a GsDevKit_home build, since it does it's own installation of 32 bit support libraries and does not use SmalltalkCI](https://travis-ci.org/GsDevKit/GsDevKit_home/builds/620348257) ...

Here's the [apt upgrade/install summary for the fresh build](https://travis-ci.org/GsDevKit/GsDevKit_home/jobs/620348261#L427-L452)

**Comment by dalehenrich** [comment]
Hold the phone! ... [The pharo 32 bit pharo vm was successfully downloaded in your travis run](https://travis-ci.org/hpi-swa/smalltalkCI/jobs/620321466#L319-L338) ... I'm going to relaunch a couple of the previously failing travis tests ... looks like something got fixed "behind the scenes"?

**Comment by dalehenrich** [comment]
@fniephaus did you flush caches before rerunning the build? My Seaside test is failing with the pharovm download error after restarted, but I flush caches first ... FWIW, I don't think GemStone was depending upon the cached pharo vm, but it might have been in which case you should flush your caches and re-run ... caching wasn't being used by the GsDevKit_home travis run (that did it's own installation of 32 bit libs for pharo) -- and this let's the pharo vm off the hook ... definitely an odd problem so far ...

**Comment by dalehenrich** [comment]
@fniephaus, I see that there is something even more interesting in your [SmalltalkCI travis run](https://travis-ci.org/hpi-swa/smalltalkCI/builds/620321459)... Specifically, one GemStone 3.5.0 test [ran successfully (Installing Pharo3.0 did not fail with 32-bit libraries error)](https://travis-ci.org/hpi-swa/smalltalkCI/jobs/620321466#L319-L336) and another GemStone 3.5.0 test [failed (Installing Pharo3.0 failed with 32-bit libraries error)](https://travis-ci.org/hpi-swa/smalltalkCI/jobs/620321462#L435-L458) ... presumably both test runs are using the exact same OS and exact same Pharo downloads ... If we can understand why one failed and the other did not we'll be in business ... 

I have some time today to look at this some more, but with these two tests within the SmalltalkCI test suite behaving differently we should be able to get to the bottom of this ...

**Comment by dalehenrich** [comment]
... haha ... never mind ... the passing GemStone test was running against the mac ...

**Comment by dalehenrich** [comment]
I have found what I think is probably diagnostic ... I was reviewing the [Metacello test runs](https://travis-ci.org/Metacello/metacello) and the [last passing Metacello cron job was #2057.1](https://travis-ci.org/Metacello/metacello/jobs/607929020), which turns out to have been running against the cache ... The next [Metacello cron job was #2058.1 and it failed](https://travis-ci.org/Metacello/metacello/jobs/611130031) ... however, it looks like this was the first cron job that ran with 16.04 and the failure appears that the caches were not being handled correctly since the error involved not finding the pharo vm properly ... I cleared the caches and reran the [Metacello job today #2601.1](https://travis-ci.org/Metacello/metacello/jobs/620384932) and it is failing with the familiar `32-bit libraries required error...

Sooo I diffed the raw log files for #2057.1 and #2601.1 and discovered that in [#2057.1 the Installing GemStone Dependencies step **was** run](https://travis-ci.org/Metacello/metacello/jobs/607929020#L424):
![image](https://user-images.githubusercontent.com/623951/70177546-6e9ae200-168f-11ea-9ef0-0173768d8a27.png)

 while in [#2601.1 the Installing GemStone Dependencies step is  absent](https://travis-ci.org/Metacello/metacello/jobs/620384932#L163):
![image](https://user-images.githubusercontent.com/623951/70177486-5034e680-168f-11ea-8e0f-8b9623ddcffb.png)

Sooo the problem seems to lie somewhere between SmalltalkCI and TravisCI, since it isn't clear to me why the `Installing GemStone Dependencies` step is no longer being executed ...

**Comment by fniephaus** [comment]
It's because the [old build ran on Trusty](https://travis-ci.org/Metacello/metacello/jobs/607929020#L21) and the [newer one on Xenial](https://travis-ci.org/Metacello/metacello/jobs/620384932#L21), and the [`smalltalk.rb`](https://github.com/travis-ci/travis-build/blob/8cbe6ab2593f5ec3099c03009c125a654763804e/lib/travis/build/script/smalltalk.rb#L214-L219) used by Travis CI does not support Xenial yet. Happy to open a pull request... but first, we need to make sure the following two parts of the installation process work on Xenial, too:

https://github.com/travis-ci/travis-build/blob/8cbe6ab2593f5ec3099c03009c125a654763804e/lib/travis/build/script/smalltalk.rb#L230-L235

and 

https://github.com/travis-ci/travis-build/blob/8cbe6ab2593f5ec3099c03009c125a654763804e/lib/travis/build/script/smalltalk.rb#L222

**Comment by dalehenrich** [comment]
[This is the script](https://github.com/GsDevKit/GsDevKit_home/blob/master/bin/utils/installOsPrereqs#L46-L51) that is being [successfully run by GsDevKit_home on Travis CI xenial](https://travis-ci.org/GsDevKit/GsDevKit_home/jobs/620348263#L259-L1037) ... and the two quoted sections were copied from the the `installOsPrereqs` scripts and note that the exact same install script isused for 14.04, 16.04 and 18.04 ... other than that I'm not sure what other "confirmation" you need ...

BTW, I'm curious why the `Installing GemStone Dependencies` step was **silently skipped** ... If there had been an outright error at that point, we wouldn't have wasted a bunch of time trying to figure out why the Pharo 32 vm stopped working ...

**Comment by fniephaus** [comment]
Sorry, I'm currently flooded with work...what I'll do when I have some time is to use a sudo-enabled Travis worker, perform the installation step manually, and see if everything works as expected. If something fails, we can find out how to fix it and once everything works, I can transform our findings into a PR for the `smalltalk.rb` on Travis' side. It's for example possible that some of the packages have a different name/version on Xenial. Hope this makes sense...

**Comment by dalehenrich** [comment]
Understood ... I'm not being directly impacted by this, but other projects that have GemStone ports could be, but I guess they'll just have to be patient ...

Keep in mind the fact that the GsDevKIt_home installOsPrereqs script has not changed vor 14.o4 through 18.04 ... so I think that all that's needed is to get the `Installing GemStone Dependencies` script running again ...

**Comment by fniephaus** [comment]
Looks like I got the [tests passing](https://travis-ci.org/hpi-swa/smalltalkCI/builds/622059071). The only line not compatible with Xenial/Bionic is:
```
sudo ln -f -s /usr/lib/i386-lin-gnu/libstdc++.so.6 /usr/lib/i386-linux-gnu/libstdc++.so
```

Shall I open a PR against Travis with the needed changes, or do we need to do something about the missing symlink, @dalehenrich?

**Comment by dalehenrich** [comment]
Sorry, I missed your comment ... the symlink is broken on my 16.04 and 18.04 machines and everything is running fine, so it is no longer needed ... I think that symlink was added as a requirement for Pharo, but it is clearly an ancient requirement ...

So go ahead and open the PR without the symlink ...

**Comment by dalehenrich** [comment]
@fniephaus, I looked at your PR and I was wondering if you put in any code that that would generate an error when the Ubunutu version moves beyond your list of supported versions? ... that way we can get immediate feedback as to the potential root cause of build issues

**Comment by fniephaus** [comment]
Sure, have a look at https://github.com/travis-ci/travis-build/pull/1827/commits/53f39c681f73836da24b0f0359ba49b0dc1450ee.

**Comment by dalehenrich** [comment]
Perfect!

**Comment by dalehenrich** [comment]
Looks like the GemStone [builds are functioning again](https://travis-ci.org/Metacello/metacello)! @Rinzwind thanks for the report
