### ISSUE TITLE
Support custom #version for loading MC Configurations

### ISSUE THREAD

**Issue by zecke** [hpi-swa/smalltalkCI#47]
Pharo Versionner doesn't create a BaselineOf but only a ConfigurationOf. It looks like when I specify #configurarion: 'ShortMessageCenter' it will always try to load #stable of that configuration. I would like to only have #stable when actually making a release and not have stable be an alias for HEAD.

Is it already possible to specify the version that should be loaded or how should it work?

**Comment by fniephaus** [comment]
@zecke thanks for the suggestion. I will add `#version` support as soon as I can :smiley:

**Comment by zecke** [comment]
Okay more than this is needed. Starting with the fact that I used "Versionner" in Pharo to create a Metacello Configuration, how can I refer to the "current" git HEAD to fetch my packages? I want to avoid putting "github://zecke/osmo-smsc:branch" in it (as somebody might have forked the repository or is using a different branch).

**Comment by dalehenrich** [comment]
Since there's not much info in the comments here, I'm curious what you are trying to do. 

I assume that you've already had the conversation about the fact that a BaselineOf is supposed to be the way to test a commit, since a BaselineOf automatically refers to the commit that the original BaselineOf was loaded from ...

I've looked at [your configuration](https://github.com/zecke/osmo-smsc/blob/master/mc/ConfigurationOfShortMessageCenter.package/ConfigurationOfShortMessageCenter.class/instance/baseline01..st) and if you follow the instructions 
[for creating a BaselineOf](https://github.com/dalehenrich/metacello-work/blob/master/docs/GettingStartedWithGitHub.md#create-baseline) and [converting an existing baseline](https://github.com/dalehenrich/metacello-work/blob/master/docs/GettingStartedWithGitHub.md#convert-an-existing-baseline), you should be able to use SmalltalkCI without any additional features...

**Comment by zecke** [comment]
Thank you for your comment. I'm not literate when it comes to Monticello and I tried to stay with just using Versionner of Pharo.

My goal would be:

* Test the latest code on travis-ci (so BaselineOf seems to be the easiest)
* Make it possible for others to load parts/all of it. This seems to bring me back to maintaining a ConfigurationOf?

Is there a way I could either:

* Use the ConfigurationOf but have the repository replaced? E.g. with a shell script I can put filetree://./mc/ into it (not that I should) or have the ConfigurationOf use the BaselineOf?

Does it make sense?

**Comment by dalehenrich** [comment]
If you use a BaselineOf then others can load your project as well. Here's the Metacello expression for loading code using a BaselineOf:

```Smalltalk
Metacello new
  baseline: 'ShortMessageCenter';
  repository: 'github://zecke/osmo-smsc:master/mc';
  get;
  load
```

If you have a local clone of the git repo, then the following is the load expression:

```Smalltalk
Metacello new
  baseline: 'ShortMessageCenter';
  repository: 'filetree://<full-path-git-repo-root>/mc';
  get;
  load
```

You need to make sure that you've got the [latest version of Metacello loaded](https://github.com/dalehenrich/metacello-work#pharo30-pharo40-and-pharo50), since the Pharo folks, don't quite keep the images up-to-date with the latest version of Metacello

**Comment by zecke** [comment]
Thanks. I created a Baseline and use it to run tests. Git branches and versions in ConfigurationOf are kind of orthogonal but how would I end up testing that "development", "stable", "bleedingEdge" work? Wouldn't I still need a #version variable for that?

**Comment by dalehenrich** [comment]
@zecke for the most part the symbolic versions map into git branches ... #stable should be equivalent to the master branch. #development is equivalent to any branch that is not the master branch ... I typically create a dev branch for quick fixes and work and when I have a more complicated issue to resolve I create a topic branch named for the issue I am working on (i.e., issue_47)... bleedingEdge would be using any non-master branch ...

**Comment by fniephaus** [comment]
`#version` is now support :smiley:

**Comment by zecke** [comment]
Thank you!

**Comment by fniephaus** [comment]
You have to thank @theseion! :)
