### ISSUE TITLE
[Squeak] Test runner breaks when a test signals a Halt or DeprecationWarning

### ISSUE THREAD

**Issue by LinqLover** [hpi-swa/smalltalkCI#470]
I did not study the source yet, but probably there should be something like `... on: TestFailure, Error, Halt do: ...` in the test execution logic.

**Comment by fniephaus** [comment]
What do you mean by "Test runner breaks"? Do you mean that the build freezes because of a debugger window? smalltalkCI cannot do a catch all on `Exception` as some mechanisms rely on exceptions (e.g. notifications for progress bars).

The relevant lines of code are:

https://github.com/hpi-swa/smalltalkCI/blob/f343d8a8b315e4a1184668e4a3ce34b92ad95332/repository/SmalltalkCI-Core.package/SCITestRunner.class/instance/runCase..st#L7-L10

https://github.com/hpi-swa/smalltalkCI/blob/f343d8a8b315e4a1184668e4a3ce34b92ad95332/repository/SmalltalkCI-Core.package/SCITestRunner.class/class/errorExceptions.st#L2-L3

(an overrides of `#errorExceptions`)

**Comment by LinqLover** [comment]
Hi Fabio, I am sorry for the imprecise description!

> What do you mean by "Test runner breaks"? Do you mean that the build freezes because of a debugger window?

The build does not freeze, but `smalltalkci` terminates immediately with a stack trace (the whole test execution, not only the execution of the current test). This happens as a consequence of an error handled via the CommandLineToolSet only. The expected behavior would be that the current test becomes red and all consecutive tests still will be executed. See [this build log excerpt](https://travis-ci.org/github/codeZeilen/SqueakByExample-english/builds/729393768#L392-L499) for an example.

Concretely, I encountered three kinds of exceptions not being caught correctly in smalltalkCI:

1. **`DeprecationWarning`,** see the build above: Probably we should patch `#errorExceptions` like this?

   ```diff
    errorExceptions 
   -	^ Halt, Error, TestFailure 
   +	^ Error, Warning, Halt, TestFailure 
   ```

   (The triple `Error, Warning, Halt` seems to be a common pattern for Squeak, see `Morph >> #fullBounds`, `WorldState >> #displayWorldSafely:`, and many others.)

   I just noted that the `TestCase` implementation in Squeak does not handle warnings either, but probably it should? At least on CI builds, I don't think we want that one arbitrary warning of whatever kind is able to break the whole test execution.
2. **`ModificationForbidden`:** I would say this isn't in the scope of this solution but rather in the scope of the Trunk because MF is still not an error, which it probably should be. See also this - still unresolved - thread on squeak-dev: [[squeak-dev] Why is ModificationForbidden not an Error?](http://forum.world.st/Why-is-ModificationForbidden-not-an-Error-td5114717i40.html)
3. **Exceptions raised from another process** that was started during the test execution:

   ```smalltalk
   testProcess
   	[self error] fork
   ```

   This is unfortunate, but I guess we cannot fix this one in smalltalkCI either, rather the test developer should care about catching exceptions in all custom processes.

What do you think? :-)

---

BTW:

> (an overrides of `#errorExceptions`)

Could you give me any pointer to these overrides? I cannot [find](https://github.com/hpi-swa/smalltalkCI/search?q=errorExceptions) anyone. :-)

**Comment by fniephaus** [comment]
> 1. `DeprecationWarning`, see the build above: Probably we should patch #errorExceptions like this?

Maybe, but it seems we should discuss this with regard to `TestCase` on the mailing list first.

> 2. `ModificationForbidden`

Uh, I'm not familiar with this one which indicates this isn't used often (or it's new). Let's add it to the list once someone reports an actual problem caused by `ModificationForbidden`.

> 3. Exceptions raised from another process that was started during the test execution:

There are many ways to break an image, smalltalkCI can only run tests on a best effort basis. In Squeak, we could force quit and fail via a `ToolSet`, but what if you want to test that a debugger was opened? BTW: smalltalkCI is used to test Squeak before building bundles (see [here](https://github.com/squeak-smalltalk/squeak-app/blob/25ebaf18249322227da1f7c767384cb35082fab7/test_image.st#L27)).

> (an overrides of #errorExceptions)

Looks like there aren't any, so `#errorExceptions` is only used to define a constant :)

**Comment by LinqLover** [comment]
> > 1. `DeprecationWarning`, see the build above: Probably we should patch #errorExceptions like this?
> 
> Maybe, but it seems we should discuss this with regard to TestCase on the mailing list first.

Alright, please see [[squeak-dev] The Inbox: SUnit-ct.129.mcz](http://forum.world.st/The-Inbox-SUnit-ct-129-mcz-td5122389.html). :-)

> > 2. `ModificationForbidden`
> 
> Uh, I'm not familiar with this one which indicates this isn't used often (or it's new). Let's add it to the list once someone reports an actual problem caused by ModificationForbidden.

I think I did encounter an actual problem raised by `ModificationForbidden` (at least it crashed my test job), but as said, this should definitely be fixed in the trunk. I just pushed the relevant thread there ...

> > 3. Exceptions raised from another process that was started during the test execution:
> 
> There are many ways to break an image, smalltalkCI can only run tests on a best effort basis. In Squeak, we could force quit and fail via a ToolSet, but what if you want to test that a debugger was opened?

Yes, I absolutely agree with that. I am actually testing debuggers in the linked repository! And it's cool that we use smalltalkCI to run all trunk tests (although IMO we should a build should be red if any tests fails, but that's another discussion) :-)

**Comment by LinqLover** [comment]
As 1. and 2. are now in the Trunk (Squeak 6.0beta) and we did not identify any concrete action for 3., I'm closing this issue. Thanks for the discussion!
