### ISSUE TITLE
Question: How to use Windows OS with GitLab ?

### ISSUE THREAD

**Issue by labordep** [hpi-swa/smalltalkCI#611]
Hi all :)
I'm beginning in CI, I have a GitLab server and actually I'm using your awesome process to test my image. So thanks !
But it's appears that this is only Linux OS and I need to test somethings on Windows.
Do you know how to do that ?

I cannot see how to do that with this file :
![image](https://github.com/hpi-swa/smalltalkCI/assets/49183340/095002ee-058e-417f-b7c5-2cb7c35f8254)

Thanks :)

**Comment by fniephaus** [comment]
Hi @labordep, I don't use GitLab CI/CD at the moment. Since smalltalkCI generally works on Windows (e.g., in a Git Bash), you should be able to use it to run tests on Windows as well. Simply download the smalltalkCI repo and call `bin/smalltalkci` should be enough to get you starting.

Hope this helps!

**Comment by labordep** [comment]
> Hi @labordep, I don't use GitLab CI/CD at the moment. Since smalltalkCI generally works on Windows (e.g., in a Git Bash), you should be able to use it to run tests on Windows as well. Simply download the smalltalkCI repo and call `bin/smalltalkci` should be enough to get you starting.
> 
> Hope this helps!

Thanks @fniephaus for your answer, I'm a beginner in CI/CD so I need to learn how to deploy smalltalkCI repo in my own GitLab server. To be sincer, actually running all tests on a Linux image with just one gitlab-ci file seems like magic for me :D
