### ISSUE TITLE
Coverage data

### ISSUE THREAD

**Issue by Nef10** [hpi-swa/smalltalkCI#91]
It would be very cool if we could generate and send coverage data to a service like [coveralls](https://coveralls.zendesk.com/hc/en-us/articles/201774865-API-Introduction) or [codecov](https://codecov.io/api#post-report)

**Comment by fniephaus** [comment]
Yes, indeed. That'd be very nice.
The testrunner supports coverage testing, I wonder what it would take to get this working. What format do coverage services for GitHub expect?

**Comment by fniephaus** [comment]
@krono how about we propose this as a SWT project?

**Comment by krono** [comment]
k

**Comment by fniephaus** [comment]
@dalehenrich we are already working on this and it would be good to get your thoughts on the following:
Running coverage tests for a repository obviously only makes sense for files that are in that repository and currently that implies the use of FileTree. A `SCIMetacelloLoadSpec` supports FileTree, but is only supposed to know how to load a project. For this to work, we need to add another slot to our configuration that holds a list of packages we want to run the coverage test against.

Now one problem: if we want to run a coverage test, we need to be able to find the corresponding file for a Class-Selector tuple. Helpers functions are already provided by FileTree, but in theory it'd be possible to load a class/method twice (and one overrides the other). If we put something like `#coverageAgainst: [ 'MyPackage']` into `#testing`, how would we be able to tell where a file for a given method is? We could certainly just check all `LoadSpec`s if they reference a FileTree directory and then check each directory for class and method, but that /can/ be ambiguous. If we add a `#coverageAgainst` to the `SCIMetacelloLoadSpec`, then the load spec knows more than just how to load a project.
Also, in the future we might support other formats that would also support coverage testing (remember that we didn't want to couple smalltalkCI with metacello too much).

My current suggestion would be to put this into `#testing` and then be happy as soon as we found one file for a method, because there can only be one class with that selector in an image anyway and it's bad practice (or even impossible without error handling) to load a class twice. What do you think?

**Comment by fniephaus** [comment]
Closing this in favor of #130 

First coverage test: https://coveralls.io/builds/5771251
